server:
  port: 8082

spring:
  application:
    name: storage-service

storage:
  s3:
    endpoint: http://localhost:9000
    region: us-east-1
    access-key: minioadmin
    secret-key: minioadmin
    bucket-name: my-bucket