server:
  port: 8082

spring:
  application:
    name: storage-service
  mvc:
    async:
      request-timeout: 60000 # 1 минута, в мс

storage:
  max-upload-size: ${STORAGE_MAX_UPLOAD_SIZE:100MB}
  s3:
    endpoint: http://localhost:9000
    region: us-east-1
    access-key: minioadmin
    secret-key: minioadmin
    bucket-name: my-bucket