server:
  port: ${REQUEST_SERVICE_PORT:8080}

spring:
  application:
    name: request-service
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:request_service_db}
    username: ${DB_USERNAME:admin}
    password: ${DB_PASSWORD:admin}
    driver-class-name: org.postgresql.Driver

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext

clients:
  conversion:
    base-url: http://${CONVERSION_SERVICE_HOST:localhost}:${CONVERSION_SERVICE_PORT:8081}/api/v1
    connect-timeout: ${CONVERSION_CONNECT_TIMEOUT:2s}
    read-timeout: ${CONVERSION_READ_TIMEOUT:10s}
    retry:
      max-attempts: ${CONVERSION_RETRY_MAX_ATTEMPTS:3}
      delay-ms: ${CONVERSION_RETRY_DELAY_MS:500}
      multiplier: ${CONVERSION_RETRY_MULTIPLIER:2}
