server:
  port: 8080

spring:
  application:
    name: request-service

  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/request_service_db
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
        format_sql: true

clients:
  conversion:
    base-url: http://localhost:8081/api/v1
    connect-timeout: 2s
    read-timeout: 10s